name: Publish to npm

on:
  push

env:
  NODE_VERSION: 10.14.1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Set up Node v${{ env.NODE_VERSION }} environment 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Build and test'
        run: |
          npm install
          npm build
          npm test
      - name: 'Prepare for publish'
        run: |
          mv package.json ./lib/package.json
          mv README.md ./lib/README.md
          cd ./lib/
      - name: Publish to NPM if version changed
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"