name: Publish to npm

on:
  push

env:
  NODE_VERSION: 10.14.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Set up Node v${{ env.NODE_VERSION }} environment 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: 'Build and test'
        run: |
          npm install
          npm run build
          npm run test
      - name: 'Prepare for library publish'
        run: |
          mv ${{ github.action_path }}/package.json ${{ github.action_path }}/lib/package.json
          mv ${{ github.action_path }}/README.md ${{ github.action_path }}/lib/README.md
          cd ${{ github.action_path }}/lib/
      - name: 'Publish to NPM if version changed'
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}